version: "3.9"

services:
  quote-nextjs-backend:
    container_name: quote-nextjs-backend
    image: navong/quote-nextjs-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    labels:
      - "traefik.http.routers.quote-nextjs-backend.rule=(Host(`quotenextjs.navong.xyz`) && PathPrefix(`/api`))"
    networks:
      - traefik-network
    restart: always

networks:
  traefik-network:
    external: true









