version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "4001:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]

